services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kmubook
      POSTGRES_PASSWORD: kmubook
      POSTGRES_DB: kmubook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
